name: Yireo Tests
on: [push]

jobs:
  integration-tests:
    name: Magento 2 Integration Tests
    container:
        image: yireo/magento2installed:2.4.7-p4
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping"
      opensearch:
        image: yireo/opensearch-dummy
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - run: |
          source .module.ini
          cd /tmp/magento
          composer config gitlab-token.gitlab.yireo.com gitlab-ci-token $CI_JOB_TOKEN
          composer config repositories.local-source path $CI_PROJECT_DIR
          composer config repositories.loki-checkout composer https://gitlab.yireo.com/api/v4/group/loki-checkout/-/packages/composer/packages.json
          composer require --prefer-source -- $COMPOSER_NAME:@dev
          export MAGENTO_MODULE=${EXTENSION_VENDOR}_${EXTENSION_NAME}
          cd /tmp/magento/dev/tests/integration/ && cp $CI_PROJECT_DIR/.gitlab-ci/install-config-mysql.php etc/install-config-mysql.php && cp $CI_PROJECT_DIR/.gitlab-ci/phpunit.xml phpunit.xml && php -d memory_limit=4G ../../../vendor/bin/phpunit -c phpunit.xml ../../../vendor/$COMPOSER_NAME/Test/Integration

